---
#This playbook deploys prometheus server with node exporter, alertmanager, grafana, firewall rules and nginx. UBUNTU 14.04 verified only. 
#One VM for prometheus,another for grafana.
 # Prometheus Server
 - hosts: prometheus 
   roles:
   - user
   - node_exporter
   - alertmanager
   - prometheus
# grafana server for dashboards
 - hosts: dash
   - grafana
