# Prometheus Alertmanager Module
# 
# credit for Init.d Script: https://github.com/William-Yeh


- name: create directory for alertmanager extracted binary
  file: path=/home/prometheus/Prometheus/{{ alertmanager_ver }} state=directory
  become: yes
  become_user: prometheus

- name: download and untar alertmanager in the newly created directory
  unarchive: src={{ alertmanager_github_ver }} dest={{ prometheus_extract_path }} copy=no owner=prometheus group=prometheus
  become: yes
  become_method: sudo

- name: copy alertmanager config file
  template: src=alertmanager.yml.j2 dest={{ alertmanager_path }}/alertmanager.yml
  become: yes
  become_user: prometheus

- name: set alertmanager variable
  copy: src="../files/etc-default-alertmanager" dest=/etc/default/alertmanager
  become: yes
  become_method: sudo

- name: copy INIT script
  template: src=alertmanager.sysvinit.debian.sh.j2  dest=/etc/init.d/alertmanager  mode="a+x"
  become: yes
  become_method: sudo

- name: set INIT status
  service: name=alertmanager enabled=yes
  become: yes
  become_method: sudo

- name: set INIT status and start
  service: name=alertmanager state=started
  become: yes
  become_method: sudo

