# Setup Prometheus as a service on SysV Init debian based systems
# Prometheus Server Module

- name: create directory for prometheus extracted binary
  file: path={{ prometheus_extract_path }} state=directory
  become: yes
  become_user: prometheus

- name: download and untar prometheus in the newly created directory
  unarchive: src={{ prometheus_github_release }} dest={{ prometheus_extract_path }} copy=no owner=prometheus group=prometheus
  become: yes
  become_method: sudo

- name: copy prometheus main config file from role's default
  template: src=../templates/prometheus.yml.j2 dest={{ prometheus_path }}/prometheus.yml
  become: yes
  become_user: prometheus

- name: copy prometheus rule file from role's default
  copy: src=../files/alert.rules dest={{ prometheus_path }}/alert.rules
  become: yes
  become_user: prometheus

- name: set prometheus variables
  copy: src="../files/etc-default-prometheus"  dest=/etc/default/prometheus
  become: yes
  become_method: sudo

- name: copy INIT script to server
  template: src="../templates/prometheus.sysvinit.debian.sh.j2"  dest="/etc/init.d/prometheus"  mode="a+x"
  become: yes
  become_method: sudo

- name: set INIT status
  service: name=prometheus enabled=yes
  become: yes
  become_method: sudo

- name: set INIT status and start
  service: name=prometheus state=started
  become: yes
  become_method: sudo


