# Install Prometheus node-exporter.
#

- name: add user prometheus
  user: name=prometheus groups=wheel append=yes
  become: yes
  become_method: sudo

- name: grant prometheus password less sudo
  lineinfile: dest=/etc/sudoers state=present regexp='^%prometheus ALL\=' line='%prometheus ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
  become: yes
  become_method: sudo

- name: create directory for node_exporter extracted binary
  file: path={{ node_exporter_path }} state=directory
  become: yes
  become_user: prometheus
  become_method: sudo

- name: download and untar node_exporter in the newly created directory
  unarchive: src={{ node_exporter_github_link  }} dest={{ node_exporter_path }} copy=no
  become: yes
  become_method: sudo
